import type { MeterBrand } from '@/types/meter-codes.types'

export const METER_BOOK: MeterBrand[] = [
  {
    name: 'Hexing',
    models: ['HXE110', 'HXE115', 'HXE130', 'HXE310'],
    providers: ['BPDB', 'DPDC'],
    verified: true,
    source: 'BPDB Official Prepaid Meter Manual',
    codes: [
      { code: '801', purpose: 'Remaining Balance', purposeBn: 'অবশিষ্ট ব্যালেন্স' },
      { code: '804', purpose: 'Meter Number', purposeBn: 'মিটার নম্বর' },
      { code: '806', purpose: 'Relay Tripping Cause', purposeBn: 'রিলে ট্রিপের কারণ' },
      { code: '810', purpose: 'Emergency Balance', purposeBn: 'জরুরি ব্যালেন্স' },
      { code: '811', purpose: 'Emergency Balance Information', purposeBn: 'জরুরি ব্যালেন্স তথ্য' },
      { code: '814', purpose: 'Current Month Usage', purposeBn: 'চলতি মাসের ব্যবহার' },
      { code: '817', purpose: 'Last Recharge Amount', purposeBn: 'সর্বশেষ রিচার্জের পরিমাণ' },
      { code: '818', purpose: 'Logoff Return Token', purposeBn: 'লগঅফ রিটার্ন টোকেন' },
      { code: '820', purpose: 'Last Month Usage', purposeBn: 'গত মাসের ব্যবহার' },
      { code: '865', purpose: 'Meter Activation', purposeBn: 'মিটার সক্রিয়করণ' },
      { code: '869', purpose: 'Sanction Load', purposeBn: 'অনুমোদিত লোড' },
      { code: '874', purpose: 'Current', purposeBn: 'কারেন্ট' },
      { code: '877', purpose: 'Voltage', purposeBn: 'ভোল্টেজ' },
      { code: '889', purpose: 'Token Sequence Number', purposeBn: 'টোকেন সিকোয়েন্স নম্বর' },
      { code: '900', purpose: 'Friendly Mode Status', purposeBn: 'ফ্রেন্ডলি মোডের অবস্থা' },
    ],
  },
  {
    name: 'Inhemeter (Single Phase)',
    providers: ['BPDB', 'DPDC'],
    verified: true,
    source: 'BPDB Official Prepaid Meter Manual',
    codes: [
      { code: '00', purpose: 'Remaining Balance', purposeBn: 'অবশিষ্ট ব্যালেন্স' },
      { code: '01', purpose: 'Current Month Usage', purposeBn: 'চলতি মাসের ব্যবহার' },
      { code: '03', purpose: 'Tariff Information', purposeBn: 'ট্যারিফ তথ্য' },
      { code: '07', purpose: 'Voltage', purposeBn: 'ভোল্টেজ' },
      { code: '08', purpose: 'Current', purposeBn: 'কারেন্ট' },
      { code: '19', purpose: 'Sanction Load', purposeBn: 'অনুমোদিত লোড' },
      { code: '30', purpose: 'Meter Number', purposeBn: 'মিটার নম্বর' },
      { code: '31', purpose: 'Last Recharge Amount', purposeBn: 'সর্বশেষ রিচার্জের পরিমাণ' },
      { code: '38', purpose: 'Remaining Emergency Balance', purposeBn: 'অবশিষ্ট জরুরি ব্যালেন্স' },
      { code: '51', purpose: 'Friendly Mode Status', purposeBn: 'ফ্রেন্ডলি মোডের অবস্থা' },
      { code: '52', purpose: 'Token Sequence Number', purposeBn: 'টোকেন সিকোয়েন্স নম্বর' },
      { code: '53', purpose: 'Last Recharge Token', purposeBn: 'সর্বশেষ রিচার্জ টোকেন' },
      { code: '54', purpose: 'Logoff Return Token', purposeBn: 'লগঅফ রিটার্ন টোকেন' },
      { code: '59', purpose: 'Remaining Emergency Balance', purposeBn: 'অবশিষ্ট জরুরি ব্যালেন্স' },
      { code: '56', purpose: 'Friendly Mode Status', purposeBn: 'ফ্রেন্ডলি মোডের অবস্থা' },
      { code: '37120', purpose: 'Meter Activation', purposeBn: 'মিটার সক্রিয়করণ' },
      { code: '89898686', purpose: 'Emergency Balance', purposeBn: 'জরুরি ব্যালেন্স' },
    ],
  },
  {
    name: 'Inhemeter (Three Phase)',
    providers: ['BPDB', 'DPDC'],
    verified: true,
    source: 'BPDB Official Prepaid Meter Manual',
    codes: [
      { code: 'C501', purpose: 'Remaining Balance', purposeBn: 'অবশিষ্ট ব্যালেন্স' },
      { code: 'C701', purpose: 'Tariff Information', purposeBn: 'ট্যারিফ তথ্য' },
      { code: 'C10', purpose: 'Meter Number', purposeBn: 'মিটার নম্বর' },
      { code: 'CL401', purpose: 'Last Recharge Amount', purposeBn: 'সর্বশেষ রিচার্জের পরিমাণ' },
      { code: 'C6011', purpose: 'Friendly Mode Status', purposeBn: 'ফ্রেন্ডলি মোডের অবস্থা' },
      { code: 'C6012', purpose: 'Friendly Mode Status', purposeBn: 'ফ্রেন্ডলি মোডের অবস্থা' },
      { code: 'C6013', purpose: 'Token Sequence Number', purposeBn: 'টোকেন সিকোয়েন্স নম্বর' },
      { code: 'C6014', purpose: 'Last Recharge Token', purposeBn: 'সর্বশেষ রিচার্জ টোকেন' },
      { code: 'C6015', purpose: 'Logoff Return Token', purposeBn: 'লগঅফ রিটার্ন টোকেন' },
      { code: '21350', purpose: 'Sanction Load', purposeBn: 'অনুমোদিত লোড' },
      { code: '37120', purpose: 'Meter Activation', purposeBn: 'মিটার সক্রিয়করণ' },
      { code: '89898686', purpose: 'Emergency Balance', purposeBn: 'জরুরি ব্যালেন্স' },
    ],
  },
  {
    name: 'Linyang',
    providers: ['BPDB'],
    verified: true,
    source: 'BPDB Official Prepaid Meter Manual',
    codes: [
      { code: '019', purpose: 'Remaining Balance', purposeBn: 'অবশিষ্ট ব্যালেন্স' },
      { code: '100', purpose: 'Meter Number', purposeBn: 'মিটার নম্বর' },
      { code: '200', purpose: 'Last Recharge Amount', purposeBn: 'সর্বশেষ রিচার্জের পরিমাণ' },
      { code: '201', purpose: 'Last Recharge Token', purposeBn: 'সর্বশেষ রিচার্জ টোকেন' },
      { code: '803', purpose: 'Current Month Usage', purposeBn: 'চলতি মাসের ব্যবহার' },
      { code: '809', purpose: 'Emergency Balance', purposeBn: 'জরুরি ব্যালেন্স' },
      { code: '865', purpose: 'Meter Activation', purposeBn: 'মিটার সক্রিয়করণ' },
    ],
  },
  {
    name: 'Eastern',
    providers: ['BPDB'],
    verified: true,
    source: 'BPDB Official Prepaid Meter Manual',
    codes: [
      { code: '010', purpose: 'Remaining Balance', purposeBn: 'অবশিষ্ট ব্যালেন্স' },
      { code: '011', purpose: 'Meter Number', purposeBn: 'মিটার নম্বর' },
      { code: '041', purpose: 'Relay Tripping Cause', purposeBn: 'রিলে ট্রিপের কারণ' },
      { code: '047', purpose: 'Current Month Usage', purposeBn: 'চলতি মাসের ব্যবহার' },
      { code: '050', purpose: 'Last Recharge Amount', purposeBn: 'সর্বশেষ রিচার্জের পরিমাণ' },
      { code: '051', purpose: 'Logoff Return Token', purposeBn: 'লগঅফ রিটার্ন টোকেন' },
      { code: '053', purpose: 'Last Month Usage', purposeBn: 'গত মাসের ব্যবহার' },
      { code: '070', purpose: 'Voltage', purposeBn: 'ভোল্টেজ' },
      { code: '071', purpose: 'Current', purposeBn: 'কারেন্ট' },
      { code: '090', purpose: 'Token Sequence Number', purposeBn: 'টোকেন সিকোয়েন্স নম্বর' },
      { code: '100', purpose: 'Friendly Mode Status', purposeBn: 'ফ্রেন্ডলি মোডের অবস্থা' },
    ],
  },
]
